### ISSUE TITLE
Welcome, Jonathan

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#1]
Jason Reeder, who's been helping with the [Arabic](https://github.com/sanskrit-lexicon/ArabicInSanskrit/) text in the Cologne Sanskrit dictionaries ,  contacted his
friend Jonathan Migliori.  Jonathan generously offered to help us with the coding of Greek text in these dictionaries,  and that work will be the focus of this repository.
# Thanks, Jonathan! and Welcome

**Comment by jmigliori** [comment]
I’m excited to help out!

**Comment by gasyoun** [comment]
@jmigliori greetings to Jonathan!

**Comment by drdhaval2785** [comment]
@jmigliori Welcome aboard

**Comment by drdhaval2785** [comment]
So @funderburkjim 
provide the tools to our new friend so as to enable him to help us.

**Comment by jsonreeder** [comment]
@jmigliori أهلا وسهلا!

**Comment by funderburkjim** [comment]
"Bienvenue" (Google Translate to the rescue!)
