### ISSUE TITLE
Greek in INM

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GreekInSanskrit#21]
Index to the Names in the Mahabharata contains Greek letters, not Greek words. @funderburkjim any clue how to find the missing pieces? @jmigliori are you still around?

[L=11620]
Varuṇa^3,¦ a serpent. § 793 (Mausalap.): XVI, 4(greek) , †119 
(only C., B. has Aruṇaḥ).

http://www.sanskrit-lexicon.uni-koeln.de/scans/INMScan/2013/web/webtc/servepdf.php?page=712

![greeels](https://cloud.githubusercontent.com/assets/80761/25547770/d9acea58-2c71-11e7-830b-4d1175005ff9.PNG)

**Comment by jmigliori** [comment]
This would be soemthing manageable.

On Friday, April 28, 2017, Mārcis Gasūns <notifications@github.com> wrote:
> Index to the Names in the Mahabharata contains Greek letters, not Greek
words. @funderburkjim any clue how to find the missing pieces? @jmigliori
are you still around?
>
> [L=11620]
> Varuṇa^3,¦ a serpent. § 793 (Mausalap.): XVI, 4(greek) , †119
> (only C., B. has Aruṇaḥ).
>
>
http://www.sanskrit-lexicon.uni-koeln.de/scans/INMScan/2013/web/webtc/servepdf.php?page=712
>
> <
https://ci6.googleusercontent.com/proxy/jYYtkSaB2zQsxPqQE6JYs5l8ZilzyqtIW9vffnXJ8blSvaOe196_L7SZuL47LvvoVjveyisdmPe1xlJO1nIrCsBRT_Mhv7UWFYFy2hKOVIBV177hS-Wesw6XMstwyhbS3O6h1QRdoDHU8NUknJtyuoBSe_ekaznR=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/80761/25547770/d9acea58-2c71-11e7-830b-4d1175005ff9.PNG
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/8LkQihuaMTaHrZTgGrYlhN5OCJqe6f77CVVyO2CpH45wi51tFw56cIx8LYxNoJ-u3IOJVpiwaq1RLlH-CQ5_f8iP1h4kdhE3dhEVpVSFi93egOCcARWo7X1ymIw0n1-kKeBAVW57s_qZitvDTR-Rj6NRpkfayw=s0-d-e1-ft#https://github.com/notifications/beacon/ALYirdjQ-6bIIc46w6GUSkCGHDjX7PJjks5r0ljJgaJpZM4NL_Gm.gif>

**Comment by Andhrabharati** [comment]
All the greek text in INM has been filled, and the issue can be closed now.
