### ISSUE TITLE
Greek in MD

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#23]
There are only 8 cases  identified as Greek text with the md (Macdonell) Sanskrit-English dictionary.

In md.txt, this Greek text is coded using Latin letters.  
I've tried to develop the Greek unicode for these.

Maybe @jmigliori  can check the work.

**Comment by funderburkjim** [comment]
```
; Case 2: <L>8017<pc>101-1<k1>jAmitra<k2>jAmitra
45021 old {#jAmitra#}¦jāmitra, {%n.%} <g>(diámetrou)</g> {%the seventh %}
45021 new {#jAmitra#}¦jāmitra, {%n.%} <lang n="greek">(διάμετρον)</lang> {%the seventh %}
```

![image](https://user-images.githubusercontent.com/6393033/27979505-95a5486e-6344-11e7-8524-fa24cf0a0302.png)

**Comment by funderburkjim** [comment]
```
; Case 3: <L>9724<pc>127-1<k1>dramma<k2>dramma
55654 old {#dramma#}¦dramma <g>(duaxmh4)</g>, {%a coin%} = sixpence.
55654 new {#dramma#}¦dramma <lang n="greek">(δραχμή)</lang>, {%a coin%} = sixpence.
```
![image](https://user-images.githubusercontent.com/6393033/27979536-bfd426a0-6344-11e7-9229-f1f450f9568d.png)

**Comment by funderburkjim** [comment]
```
; Case 4: <L>10986<pc>149-2<k1>paNkti<k2>paNkti
64279 old {#paNkti#}¦paṅk-tí, {%f.%} set of five <g>(pentáz)</g> series 
64279 new {#paNkti#}¦paṅk-tí, {%f.%} set of five <lang n="greek">(πεντάϛ)</lang> series 
```

![image](https://user-images.githubusercontent.com/6393033/27979566-e21cb132-6344-11e7-86de-e884f7403f29.png)

**Comment by funderburkjim** [comment]
```
; Case 5: <L>10999<pc>149-2<k1>paYcaka<k2>paYcaka
64353 old <>number five <g>(pentáz)</g>; ({@páñca@}) {@-kapāla,@} {%a.%} 
64353 new <>number five <lang n="greek">(πεντάϛ)</lang>; ({@páñca@}) {@-kapāla,@} {%a.%} 
```
![image](https://user-images.githubusercontent.com/6393033/27979588-0f929f50-6345-11e7-9a98-d32e97a85462.png)

**Comment by funderburkjim** [comment]
```
; Case 6: <L>13922<pc>223-3<k1>mA<k2>mA<h>1
89963 old {#mA#}¦mā́, {%prohibitive ad. cj.%} (= Gk. <g>mh4</g>) not, 
89963 new {#mA#}¦mā́, {%prohibitive ad. cj.%} (= Gk. <lang n="greek">μή</lang>) not, 
```
![image](https://user-images.githubusercontent.com/6393033/27979613-38ee9c8c-6345-11e7-9a50-f7186a7a742f.png)

**Comment by funderburkjim** [comment]
```
; Case 7: <L>19458<pc>351-2<k1>su<k2>su
135501 old <>{%Gk.%}<g>eu{??}</g>: {%cp.%} uṣu, ū shu, {%and%} u loka] good, well, 
135501 new <>{%Gk.%}<lang n="greek">εύ {??}</lang>: {%cp.%} uṣu, ū shu, {%and%} u loka] good, well, 
```
### Note this is marked with question -- Is question needed?

![image](https://user-images.githubusercontent.com/6393033/27979662-a5566ce2-6345-11e7-988e-68faf58c0baf.png)

**Comment by funderburkjim** [comment]
```
; Case 8: <L>19513<pc>353-2<k1>sundara<k2>sundara
136129 old <>sū-nára, sū-nṛta; {%Gk.%}<g>a3nr, a-n-d-róz</g>] beautiful, <lbinfo n="4"/>
136129 new <>sū-nára, sū-nṛta; {%Gk.%}<lang n="greek">ἀ-νήρ, ἀ-ν-δ-ρός</lang>] beautiful, <lbinfo n="4"/>
```
![image](https://user-images.githubusercontent.com/6393033/27979688-d34173e0-6345-11e7-845a-a60a59f51fbc.png)

**Comment by funderburkjim** [comment]
```
; Case 9: <L>20666<pc>381-2<k1>horA<k2>horA
145975 old {#horA#}¦horā, {%f.%} [<g>w11ra</g>] hour; half of a sign of 
145975 new {#horA#}¦horā, {%f.%} [<lang n="greek">ὥρα</lang>] hour; half of a sign of 
```
![image](https://user-images.githubusercontent.com/6393033/27979706-fd1178c8-6345-11e7-81dd-8f11bc683bbd.png)

**Comment by gasyoun** [comment]
> Note this is marked with question -- Is question needed?

Can't see the question mark.

**Comment by funderburkjim** [comment]
The question mark (case 7) occurs in the digitization, not the print.  Maybe because of diacritics on the Greek 'nu' letter.

**Comment by gasyoun** [comment]
> The question mark (case 7) occurs in the digitization, not the print. Maybe because of diacritics on the Greek 'nu' letter.

Anyway no need to retain it.

**Comment by jmigliori** [comment]
The only one that needs to be changed is Case 7, which should be εὖ instead of εύ. Welcome to the incredibly fussy world of Ancient Greek accent rules and diacritics.

**Comment by gasyoun** [comment]
> Welcome to the incredibly fussy world of Ancient Greek accent rules and diacritics.

Lasciate ogni speranza, voi ch'entrate

**Comment by jmigliori** [comment]
👏 👏 👏

On Friday, July 28, 2017, Mārcis Gasūns <notifications@github.com> wrote:
> Welcome to the incredibly fussy world of Ancient Greek accent rules and
diacritics.
>
> Lasciate ogni speranza, voi ch'entrate
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/zzWp--IYFfLKijbJyTWHM4VqRqPjkcyKfUCMhMCxgulyBRxgyv9D62B9S3ue5BZWeXkR3oeQnsBNGoGRMDDw3whDgMj31VUqkH7kdGb8Vpy-0c6FZ9HnN7HVvnvIM9OANdDPdq5cHMaZLAWmTLMT3deO6XZZYg=s0-d-e1-ft#https://github.com/notifications/beacon/ALYirU7Eqcln3tAi9VoxfL_XkA76CkqVks5sSjbkgaJpZM4ORg9Y.gif>

**Comment by funderburkjim** [comment]
### correction to case 7
Done per @jmigliori .  Also, question mark removed.
