### ISSUE TITLE
Greek in Cappeller Sanskrit English

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#26]
There are only 3 instances of Greek alphabet so far identified in cae.txt.

#### Case 1, headword 'a'
```
2 {#a#}¦ ·{#an#} neg. prefix, corresponding to Gr. <lang n="greek">ἀ ἀν</lang>, Lat. in, Germ.
```
![image](https://user-images.githubusercontent.com/6393033/32033185-12adb806-b9d9-11e7-983a-75dad72604a4.png)

#### Case 2, headword 'dus'
```
{#dus#}¦ ·(°--) = Gr. <lang n="greek">δυς</lang>.
```
![image](https://user-images.githubusercontent.com/6393033/32033227-5a5ba56e-b9d9-11e7-8386-2fdc1c010a99.png)

#### Case 3, headword 'su'
```
often °-- in adj., adv., & subst. = Gr. <lang n="greek">εν</lang> (opp. {#dus#}).
```
![image](https://user-images.githubusercontent.com/6393033/32033259-9f6b5c3a-b9d9-11e7-8a0c-3b2d1e4262ec.png)

@jmigliori   Would you take a look at these and correct as needed?
I couldn't see how to get a preformed accent over ν in Case 3.

**Comment by gasyoun** [comment]
> <lang n="greek">εν</lang>

εὐ

**Comment by jmigliori** [comment]
The first two and @gasyoun ‘s amendment are correct

**Comment by funderburkjim** [comment]
Thanks to all!

**Comment by drdhaval2785** [comment]
Installation already over. Closing.
```
<L>36978<pc>619<k1>su<k2>su/<h>2
2 {#su/#}¦ ({#sU/#}) <ab>adv.</ab> well, indeed (strengthening and assevering);
often °— in <ab>adj.</ab>, <ab>adv.</ab>, & subst. = Gr. <lang n="greek">εὐ</lang> (<ab>opp.</ab> {#dus#}).
<LEND>
```
