### ISSUE TITLE
Greek in INM, 2

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GreekInSanskrit#27]
At `airāvata` in INM I find (searching for `Airāvata` did not work at all, so it's a bug.

`564 (Mātalīyop.): V, 103 (greek)`

![103](https://user-images.githubusercontent.com/80761/46628283-b97da000-cb45-11e8-989a-347b7525b5fc.PNG)

See http://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/servepdf.php?dict=inm&page=26

Easy to fix.

**Comment by Andhrabharati** [comment]
All the greek text in IMM has been filled, and the issue can be closed now.
