### ISSUE TITLE
Greek in GRA

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GreekInSanskrit#28]
229 cases [as in other dictionaries noted as (greek)] in Grassman Wörterbuch zum Rig Veda.

![rta](https://user-images.githubusercontent.com/80761/54482273-ba7bd180-4849-11e9-9dcd-706d927fa2a5.PNG)

```
 von ar 10 (gr. (greek) ), dem lat. ratus 
```

@jmigliori should I make screenshots of all the cases or just a list of headwords would be enough to fill the gap? Thanks.

**Comment by jmigliori** [comment]
Screenshots would make it a little easier on my end, but if that’s harder for you, I can certainly do fine with headwords

**Comment by gasyoun** [comment]
> Screenshots would make it a little easier on my end

If in such case you will not need to open the source code, it would be great. I'm ready for monkey work.

> I can certainly do fine with headwords

https://www.sanskrit-lexicon.uni-koeln.de/scans/GRAScan/2014/web/index.php

Guess just a list will not work?

```
Msa
akzu
agra
aGa
aNgiras
aja
ajra
aDi
an
anu
anta
antra
anDa
anDas
apaciti
amatra
amfta
amBas
ar
arh
aS
aSru
asfj
ah
ahan
ahi
A
Atman
Ama
Ardra
ASu
izira
Ikz
ukz
uru
urvarA
Urj
UrRavABi
UrDva
fC
fta
fdu
fhat
kapanA
kam
karkari
karz
kalaSa
kalA
kuB
kulAya
kratu
kzap
kzam
kzamya
kzi
kzura
kzRu
Kid
gfD
gnA
graT
Ga
ca
cakra
caKvas
cAy
cAza
ci
CAga
jar
jAmAtf
jeh
jYA
taMs
taku
takzan
tanu
tfd
trita
daMs
dakziRa
dam
dama
dA
dAna
dAnu
dAru
du
dfti
dvAr
Danu
DAv
DenA
na
nakti
naqa
naB
nama
navedas
naS
nas
nu
paj
pajra
paraSu
parA
parRa
pavi
pitva
piSuna
pIq
pIvan
pIvas
pU
pfc
pfdAku
pfSni
prati
pravat
prAtar
Par
bahu
bAhu
buD
Bakz
Ban
Basad
BAs
Bur
Buraj
BU
Bf
Bfjj
BrAj
BrAtf
BrU
maKa
maKasy
majman
mad
maDu
maDya
man
manA
mar
mA
mAMScatu
mAkis
mAkI
mAkIm
mAti
mAyA
mih
muc
meka
meDA
yat
yas
ranDra
riK
riS
vAGat
vfj
veSa
veSia
Sam
SU
SnaT
Sravas
saG
sac
satyaSravas
santya
sama
sah
su
suBasad
sU
stAmu
stiyA
svAd
hAridrava
hiruk
```

**Comment by gasyoun** [comment]
@funderburkjim `Die griechischen Formen (greek)` which I see missing at our end is fixed at https://vedaweb.uni-koeln.de/rigveda/view/id/01.015.12

`santya,a., gut, wohlgesinnt [von sát, sánt -- dem Part. von as und wol dem griech. ὅσιος zu vergleichen]`

**Comment by funderburkjim** [comment]
The vedaweb greek data now incorporated in our digitization gra.txt.
Reference: https://github.com/sanskrit-lexicon/csl-orig/tree/master/v02/gra/greek

**Comment by gasyoun** [comment]
> The vedaweb greek data now incorporated in our digitization gra.txt.

Hurray!
