### ISSUE TITLE
Acknowledgments

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#32]
I think we need to add Jonathan's name in the 'License of Digital Edition' for MW72.

Each of the dictionaries has a link to 'License of Digital Edition' in the main page of the web displays, 

If you click here for MW72 on the home page of the Sanskrit lexicon:

![image](https://user-images.githubusercontent.com/6393033/64213347-aae55900-ce7a-11e9-8ba2-6bab8d89b1c0.png)

You will get here. And if you click on the 'License of Digital Edition' 
![image](https://user-images.githubusercontent.com/6393033/64213397-d8320700-ce7a-11e9-98ce-71e663dafb57.png)

You will see the mw72header.xml document:

![image](https://user-images.githubusercontent.com/6393033/64213451-0a436900-ce7b-11e9-972b-e6e86f8839ca.png)

It is within this mw72header.xml file that I think acknowledgment should be added.

**Comment by funderburkjim** [comment]
## The mwheader.xml example

Here is the [License of digital edition for MW](https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/downloads/mwheader.xml).

Note the following clause  (respStmt) for Greek data entry in MW.

```
<respStmt>
<resp>Greek data entry</resp>
<name>Wendy Teo</name>
</respStmt>
```

I suggest a similar clause be put in mw72header.xml :
```
<respStmt>
<resp>Greek data entry</resp>
<name>Jonathan Migliori</name>
<note>2017-2019</note>
</respStmt>
```

Note that I have put in a 'note' tag as an indication of when Jonathan did the work. 
Although this tag is absent in the mw72header.xml example,  it is consistent with the
[TEI respStmt](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-respStmt.html).   

If others agree with this format, I'll go ahead and modify the mw72 header.

**Comment by funderburkjim** [comment]
## Other acknowledgments needed

I don't currently have a list of other contributions similar to Jonathan's for mw72 greek.

Maybe others can give a hand here so we can get the acknowledgments up to date.

**Comment by drdhaval2785** [comment]
I agree we should add Jonathan's name in acknowledgements.

I am not sure whether Sampada's name figures in acknowledgements. If not, should figure at appropriate dictionaries.

**Comment by gasyoun** [comment]
> I agree we should add Jonathan's name in acknowledgements.

So do I.

> I am not sure whether Sampada's name figures in acknowledgements. If not, should figure at appropriate dictionaries.

Full support.

**Comment by funderburkjim** [comment]
## Jonathan acknowledged

The xxxheader.xml files have been updated for acknowledging @jmigliori 's greek text input.

Will review acknowledgments for @sanskritisampada and @jsonreeder.

**Comment by jmigliori** [comment]
Thanks for adding me to the acknowledgments. I appreciate it! I noticed that my last name is misspelled though; it should be “Migliori"

**Comment by funderburkjim** [comment]
@jmigliori  --  mea culpa on misspelling.  Now corrected.

**Comment by gasyoun** [comment]
@funderburkjim closable?

**Comment by funderburkjim** [comment]
Here are where @sanskritisampada  is acknowledged:
```
ae/aeheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
ap90/ap90header.xml:     <name>Dr. Sampada Savardekar Thomas</name>
ben/benheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
bor/borheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
mw/mwheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
mw72/mw72header.xml:     <name>Dr. Sampada Savardekar Thomas</name>
mwe/mweheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
pd/pdheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
pwg/pwgheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
skd/skdheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
vcp/vcpheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
wil/wilheader.xml:     <name>Dr. Sampada Savardekar Thomas</name>
```

**Comment by funderburkjim** [comment]
Here are where @jmigliori is acknowledged:
```
cae/caeheader.xml:     <name>Jonathan Migliori</name>
md/mdheader.xml:     <name>Jonathan Migliori</name>
mw72/mw72header.xml:     <name>Jonathan Migliori</name>
pw/pwheader.xml:     <name>Jonathan Migliori</name>
pwg/pwgheader.xml:     <name>Jonathan Migliori</name>
wil/wilheader.xml:     <name>Jonathan Migliori</name>
```

**Comment by funderburkjim** [comment]
Here is where @jsonreeder is acknowledged .
```
mw/mwheader.xml:       <name>Jason Lyle Reeder</name>
mw72/mw72header.xml:     <name>Jason Lyle Reeder</name>
pw/pwheader.xml:      <name>Jason Lyle Reeder</name>
pwg/pwgheader.xml:       <name>Jason Lyle Reeder</name>
wil/wilheader.xml:       <name>Jason Lyle Reeder</name>
```

I think the acknowledgments for @sanskritisampada and @jmigliori  @jsonreeder are complete -- let me know otherwise.

**Comment by gasyoun** [comment]
> Dr. Sampada Savardekar Thomas

Dr. Sampada Savardekar**,** Thomas?

**Comment by funderburkjim** [comment]
No, there is no comma.
