### ISSUE TITLE
Greek text in Benfey and BOESP verses

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#33]
The Benfey dictionary has about 1300 lines with Greek text.  Currently, this is represented only by a placeholder markup `<lang n="greek"></lang>`.  

It would be an enhancement to have the appropriate Unicode Greek text.

**Comment by drdhaval2785** [comment]
@jmigliori 
Would you be interested in this work?
This time it would be really easy. You can directly write in the ben.txt file and do necessary additions.
You can then push / do a pull request.

**Comment by funderburkjim** [comment]
@jmigliori  is working on Greek in Lanman at the moment, I believe.

@drdhaval2785   Will let you manage Benfey Greek with Jonathan.

**Comment by jmigliori** [comment]
@drdhaval2785 I could take this on after I finish with Lanman, which I’m about ¼ of the way through

**Comment by drdhaval2785** [comment]
Sure @jmigliori . Let me know when you are done with Lanman. Look forward to work with you.

**Comment by gasyoun** [comment]
>  I’m about ¼ of the way through

Good news.

**Comment by funderburkjim** [comment]
@jmigliori 

Hello again, Jonathan.  Hope all has been well for you.

In doing some work recently with Benfey dictionary,  I came across this issue from late last year.

Are you still up for adding Greek text to Benfey dictionary?

**Comment by funderburkjim** [comment]
Incidentally, Jonathan DID finish Greek in Lanman --- although I can't find issues on this  (@jmigliori  do you
recall if there was a Github issue regarding Greek in Lanman?)

**Comment by jmigliori** [comment]
Hi @funderburkjim ! I do not recall any GitHub issues with Lanman, but that was a while ago.

As for Benfey, I’m pretty tied up with the start of the school year so I’m hesitant to take on something I might not be able to complete in a timely manner. How does the amount of Greek compare to other dictionaries?

**Comment by funderburkjim** [comment]
Jonathan -- understood.

There is a summary of the current status of Greek in Sanskrit dictionaries at #36.
Ultimately, we would like you to provide Greek for all the remaining 7 dictionaries with Greek.
But it is likely that providing Greek text for Benfey is a bigger task than you want to undertake at this time.

## Boehtlingk Indishe spruche, volume 1
We are currently working on the digitization of a text of short 'sayings'.
The work is in three volumes, and we are focusing on volume 1.
The sayings are in Sanskrit, and there are translations in German.

In volume 1, for a small number (8) of these sayings, the author also presents a Greek translation.
[Greek.translations.in.boesp-1.pdf](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7145450/Greek.translations.in.boesp-1.pdf)

Recently, another contributor has provided a possible digitization of these into Greek Unicode:
[Greek.Translations.in.boesp-1_ansi.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7145466/Greek.Translations.in.boesp-1_ansi.txt)

[reference for this](https://github.com/funderburkjim/boesp-prep/issues/16)


**Perhaps you could proofread this?**    and provide a corrected version.

## future work on remaining dictionaries.

When you have time and inclination to tackle Greek for the remaining dictionaries,
make a comment here or in a new issue,  and I'll work with you to develop the resources (digitization and
pdf) you need.   Sound like a plan?

**Comment by funderburkjim** [comment]
## Boehtlingk Indishe spruche, volume 2

@jmigliori  Discovered that a similar task needs to be done with volume 2.
Here are the resources provided by @Andhrabharati: 
[Greek-2.pdf](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7145515/Greek-2.pdf)
[Greek.Translations.boesp-2.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7145517/Greek.Translations.boesp-2.txt)

If you undertake the volume 1 proofreading, maybe you will also be able to do the same for volume 2.

**Comment by jmigliori** [comment]
[Greek.Translations.in.boesp-1_ansi-corrected.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7145687/Greek.Translations.in.boesp-1_ansi-corrected.txt)
[Greek.Translations.boesp-2.-corrected.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7145688/Greek.Translations.boesp-2.-corrected.txt)

Here are the corrected versions of those Boehtlingk sayings. There were a few minor things.

I could probably knock out those shorter dictionaries pretty quickly. Would I be able to take on BHS, GST, and VEI?

**Comment by gasyoun** [comment]
> I could probably knock out those shorter dictionaries pretty quickl

Is not he a helping hand? Good to see you around again.

**Comment by funderburkjim** [comment]
Jonathan -- Andhrabharati also has the verses from volume 3.  Here are the files:
[Greek-3.pdf](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7146497/Greek-3.pdf)
[Greek.Translations.boesp-3.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7146498/Greek.Translations.boesp-3.txt)

The task here is to proofread,  but
also to enter the last 4 verses.


I'll get onto preparation for you of bhs, gst, and vei.

**Comment by Andhrabharati** [comment]
@funderburkjim 

when you take up BUR for Greek, pl. have a look at https://github.com/sanskrit-lexicon/csl-orig/issues/607#issuecomment-914916287

**Comment by jmigliori** [comment]
Here are the corrected verses from Volume 3:

[Greek.Translations.boesp-3-corrected.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7148364/Greek.Translations.boesp-3-corrected.txt)

**Comment by funderburkjim** [comment]
Am closing this issue. 
The Greek text related to boesp verses has been provided; the proofread versions are in the 'corrected'
files provided by @jmigliori above.

Will open separate issue related to Greek in Benfey,  which will remain open.
