### ISSUE TITLE
Greek in SNP

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#34]

**Comment by funderburkjim** [comment]
According to the digitization of SNP (Meulenbeld's Sanskrit Names of Plants), there is one instance of Greek text, under headword *barbara* : 

![image](https://user-images.githubusercontent.com/6393033/67973447-e84e3480-fbe6-11e9-97c1-8121bf269677.png)

An internet search for 'unguis odoratus Greek'  leads to https://en.wikipedia.org/wiki/Onycha which in turn leads to [ὄνυξ](https://en.wiktionary.org/wiki/%E1%BD%84%CE%BD%CF%85%CE%BE), which is very close to the printed text, except for a variance in the accent over the 'o' (omicron).

This suggest the following for the digitization (line 2819)
```
<lang n="greek">ὄνυξ</lang> of Dioscorides, unguis odoratus; see Dietz, p. 57; b) <bot>EUPHORBIA
```

And this change has been made.

**Comment by gasyoun** [comment]
> ὄνυξ, which is very close to the printed text, except for a variance in the accent over the 'o' (omicron).

ὄνυξ -> ὀνυξ

**Comment by funderburkjim** [comment]
Thanks.  Made change to accent.  Here are the steps:

* in local installation, 
   * in csl-orig/v02/snp/snp.txt,  made the change manually.
   * git push origin master
* In Cologne installation, 
   * in csl-orig,  `git pull origin master`
   * in csl-pywork/v02:  ` sh generate_dict.sh snp  ../../SNPScan/2020/`

Verify: the Cologne displays (e.g. in simple search, under hw = barbara) show the change in accent.

For a local installation to get the change:
* In local installation,
   * in csl-orig,  `git pull origin master`
   * in csl-pywork/v02:  ` sh generate_dict.sh snp  ../../snp`

**Comment by funderburkjim** [comment]
## Question regarding semantic versioning

@drdhaval2785  What should be added to the above in relation to the [semantic versioning proposal](https://github.com/sanskrit-lexicon/csl-orig/issues/6) ?

**Comment by gasyoun** [comment]
> What should be added to the above in relation

Guess it's 1.0.1
