### ISSUE TITLE
a, t, v, Librae, and γ 

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/GreekInSanskrit#35]
[ID=177186] MW

Before: a, t, v, Librae, and γ 
After: α, ι, ν, Librae, and γ 

![radha](https://user-images.githubusercontent.com/80761/75479132-16366080-59b0-11ea-881d-c152e40dcd91.PNG)

@jmigliori agrees?

**Comment by jmigliori** [comment]
That’s correct!

**Comment by funderburkjim** [comment]
Corrected.  

Hi, Jonathan!.
