### ISSUE TITLE
Which dictionaries have Greek text

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#36]
This is a review of which sanskrit-lexicon dictionaries have Greek text,
and how much;
and of these, which have been translated already,

These summaries as of 09-09-2021.

## texts with greek (greek done)
mw 1156 greek in 736 lines  (By Wendy/Peter)

Done by Jonathan:
mw72 1665 greek in 1463 lines
pwg 398 greek in 398 lines
pw 186 greek in 178 lines
lan 1012 greek in 868 lines
gra 228 greek in 226 lines
md 9 greek in 9 lines

Done (Not sure by whom):
wil 23 greek in 20 lines
cae 3 greek in 3 lines
snp 1 greek in 1 lines
stc 1 greek in 1 lines
yat 1 greek in 1 lines

**Comment by funderburkjim** [comment]
## texts with greek (greek NOT DONE)

ben 1513 greek in 1276 lines
bhs 3 greek in 3 lines
bop 1718 greek in 1372 lines
bur 677 greek in 667 lines
gst 13 greek in 11 lines
inm 10888 greek in 9612 lines
vei 147 greek in 112 lines

As of 5/23/2022  the greek can be considered 'DONE'.

**Comment by funderburkjim** [comment]
## dictionaries with no greek text
acc 0 greek 
ae 0 greek 
ap 0 greek 
ap90 0 greek 
bor 0 greek 
ccs 0 greek 
ieg 0 greek 
krm 0 greek 
mci 0 greek 
mwe 0 greek 
pd 0 greek 
pe 0 greek 
pgn 0 greek 
pui 0 greek 
~~sch 0 greek~~  
shs 0 greek 
skd 0 greek 
vcp 0 greek

**Comment by funderburkjim** [comment]
## program
Here is the Python program that generated above data from csl-orig files

Program location in folder xampp/htdocs/cologne/A/B/
And csl-orig is xampp/htdocs/cologne/csl-orig/

Program invocation is `python greekchk.py greekchk.txt`.

Filename of program below ends in '.txt' to accomodate Github.

[greekchk.py.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7145364/greekchk.py.txt)

**Comment by gasyoun** [comment]
Who is Wendy?

**Comment by funderburkjim** [comment]
A colleague or student of Malcolm or Peter: Mentioned in [mw license](https://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2020/web/mwheader.xml).

**Comment by Andhrabharati** [comment]
Just by chance, got onto few greek words in SCH (listed by @funderburkjim as having no greek text)!!
**But, these are not filled in Greek script, and are with a different 'marking'!!**

`<L>10712`
°{%kukāmin%}¦ = [greek]duserOs[greek], Bodhicaryāv. 8, 73.
[greek]duserOs[greek] to be changed to `<lang n="greek">δυσέρως</lang>`
![image](https://user-images.githubusercontent.com/75209130/145998464-ef295a71-d95c-4c57-9c1e-b1e3dce83214.png)

`<L>13962`
{%juka%}¦ m. [greek]zugon[greek] die Wage im Tierkreise, M. Müller, Ren. 326. Richtig {%jūka%}, vgl. Ind. St. 2, 259.
[greek]zugon[greek] to be changed to `<lang n="greek">ζυγόν</lang>`
![image](https://user-images.githubusercontent.com/75209130/146002675-f4e51d87-7dd3-47a6-a25f-7c2e13399fd5.png)

`<L>14019`
{%jyeṣṭhamalla%}¦ superior (cf. [greek]triaktEr[greek]) Harṣac. 85, 15.
[greek]triaktEr[greek] to be changed to `<lang n="greek">τριαϰτήρ</lang>`
![image](https://user-images.githubusercontent.com/75209130/146002136-aff5bdb8-7c81-4a54-b767-280853513c86.png)

`<L>18405`
5. {%pārtha%}¦ m. und {%pārthona%} m. = [greek]parthenos[greek], die Jungfrau im Tierkreise, M. Müller, Ren. 326.
[greek]parthenos[greek] to be changed to `<lang n="greek">παρϑένος</lang>`
![image](https://user-images.githubusercontent.com/75209130/146001847-00a7ddd9-b8fa-4b42-b814-2b8aa5927455.png)

`<L>24693`
{%Śakasthāna%}¦ , l. [greek]ZakastEnE[greek]
[greek]ZakastEnE[greek] to be changed to `<lang n="greek">Ζαϰαστηνη</lang>`
![image](https://user-images.githubusercontent.com/75209130/146001686-bb0b9c25-d151-45b9-ad98-ac62d1d9250e.png)

@jmigliori 
Pl. look at these and confirm; I see that the ω is upside-down in the first entry above- does it indicate some special notation?

**Comment by Andhrabharati** [comment]
@funderburkjim 
Checking further, to see if any more are present in the whole of CDSL texts, has led to another finding.

PE has entries not to be transcribed into Devanagari, like-
Greek (ग्रेएक्), Hippocraitus (हिप्पोच्रैतुस्), ...

**So this needs to be posted under the other thread to treat such cases.**

**Comment by jmigliori** [comment]
There doesn’t seem to be a variant of omega or another letter that looks
like that. δυσέρως is indeed a word (meaning “madly or disastrously
loving”) and I can’t find any other Greek words beginning with δυσέρ that
this could be. δυσέρως is correct.

**Comment by Andhrabharati** [comment]
SCH seems yet to be corrected for the above.

When @funderburkjim does them, this issue can be closed.

**Comment by Andhrabharati** [comment]
Also @funderburkjim might consider updating the three lists posted above--

- texts with greek (greek done)
- texts with greek (greek NOT DONE)
- dictionaries with no greek text

**Comment by funderburkjim** [comment]
## revised greekchk
Also notice in ben/bop there are a few 'empty' instances.
This tabulation based on the current files: csl-orig/v02/xxx/xxx.txt

```
acc 0 greek in 0 lines
ae 0 greek in 0 lines
ap 0 greek in 0 lines
ap90 0 greek in 0 lines
ben 1265 greek in 1078 lines (22 empty instances) (now filled - see comments below)
bhs 3 greek in 3 lines
bop 1370 greek in 1099 lines (15 empty instances) (now filled - see comments below)
bor 0 greek in 0 lines
bur 669 greek in 665 lines
cae 3 greek in 3 lines
ccs 0 greek in 0 lines
gra 228 greek in 226 lines
gst 13 greek in 11 lines
ieg 0 greek in 0 lines
inm 10713 greek in 9439 lines
krm 0 greek in 0 lines
mci 0 greek in 0 lines
md 9 greek in 9 lines
mw 1156 greek in 736 lines
mw72 1664 greek in 1462 lines
mwe 0 greek in 0 lines
pd 0 greek in 0 lines
pe 0 greek in 0 lines
pgn 0 greek in 0 lines
pui 0 greek in 0 lines
pwg 398 greek in 398 lines
pw 186 greek in 178 lines
sch 5 greek in 5 lines
shs 0 greek in 0 lines
skd 0 greek in 0 lines
snp 1 greek in 1 lines
stc 1 greek in 1 lines
vcp 0 greek in 0 lines
vei 150 greek in 113 lines
wil 23 greek in 20 lines
yat 1 greek in 1 lines
lan 1012 greek in 868 lines
```

**Comment by funderburkjim** [comment]
The revised program
 [greekchk_program.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/8758431/greekchk_program.txt)

**Comment by funderburkjim** [comment]
The 'non-sanskrit- headwords in PE and IEG -- No idea how to improve the situation there.

**Comment by Andhrabharati** [comment]
@funderburkjim 
> This tabulation based on the current files: csl-orig/v02/xxx/xxx.txt

where are the updated files? I am not able to see them at csl-orig/vo2/...

> ben 1265 greek in 1078 lines (22 empty instances)
> bop 1370 greek in 1099 lines (15 empty instances)

and what are these empty strings- yet to be filled?

**Comment by funderburkjim** [comment]
Empty strings occur 
* ben: in the ADDENDA AND CORRIGENDA.
* bop: in (a) front matter and (b) ADDENDA ET EMENDANDA.

Maybe you have separated out these sections into different files in your versions of these two
dictionaries?

**Comment by Andhrabharati** [comment]
Yes, I did separate the "full-book files" of cdsl into parts, while I was working on them.

And those parts have all the `<lang>` strings filled up.

**Comment by funderburkjim** [comment]
> where are the updated files? 

Not sure what files you are looking for.  
The 'revised greekchk' table was generated locally by running the greekchk program;  this
program reads each of the local csl-orig/v02/xxx/xxx.txt files.

**Comment by funderburkjim** [comment]
Would you refer me to links for the additional parts of ben,bop which have the greek text filled in?

**Comment by Andhrabharati** [comment]
BOP parts- https://github.com/sanskrit-lexicon/csl-devanagari/issues/40#issue-1219008072

**Comment by Andhrabharati** [comment]
BEN parts-
[ben_Addenda.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/8765106/ben_Addenda.txt)
[ben_FrontPages.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/8765108/ben_FrontPages.txt)
[ben_abbr.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/8765151/ben_abbr.txt)
[ben_ls.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/8765152/ben_ls.txt)
[BEN language tags.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/8765157/BEN.language.tags.txt)

**Comment by Andhrabharati** [comment]
> Not sure what files you are looking for.

I was looking for the `<lang>` strings filled-up files.

**Comment by funderburkjim** [comment]
The csl-orig repository files at Github have the `<lang>` strings filled in.  
e.g. https://github.com/sanskrit-lexicon/csl-orig/blob/master/v02/ben/ben.txt

**Comment by funderburkjim** [comment]
lang tag filled in for frontmatter and addenda for bop.  
Refer https://github.com/sanskrit-lexicon/BOP/issues/1.

**Comment by funderburkjim** [comment]
lang tag filled in for addenda section of ben.
Refer https://github.com/sanskrit-lexicon/BEN/issues/6.


Now empty lang tags filled for ben/bop.
