### ISSUE TITLE
Greek in BHS dictionary

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#37]
BHS = Buddhist Hybrid Sanskrit

3 instances marked as Greek text in digitization to be filled.

**Comment by funderburkjim** [comment]
First one so trivial I can do it:

```
<L>993<pc>033,1<k1>anurUpe<k2>anu-rUpe

<div n="lb">Pali anu-tīre etc. (CPD s.v. anu, b, <lang n="greek">𝛿</lang>). In the parallel
```

![image](https://user-images.githubusercontent.com/6393033/132921492-f8a0c57e-129a-4fc9-8292-d56780464360.png)

**Comment by funderburkjim** [comment]
Second one for @jmigliori:

```
<L>2174<pc>075,1<k1>avaSaMsyati<k2>avaSaMsyati
<div n="lb">we except the AV noun avaśas, <lang n="greek”>ἅπ. λεγ.</lang>. Moreover no
```

![image](https://user-images.githubusercontent.com/6393033/132921627-7a593588-88f2-4897-8b2f-9bdf77bcafa1.png)

**Comment by funderburkjim** [comment]
And last one for @jmigliori 

```
<L>4868<pc>183,1<k1>kimpala<k2>kimpala
<div n="lb">musical instrument; pw suggests loan from Gk. <lang n="greek”>κύμβαλον</lang>:
```

![image](https://user-images.githubusercontent.com/6393033/132921813-ec50e47d-7607-4509-aa32-c7e56aa52dfd.png)

**Comment by funderburkjim** [comment]
@jmigliori 

Just edit the two comments above and enter Greek text `<lang n="greek">GREEK TEXT HERE</lang>`.

**Comment by jmigliori** [comment]
all set @funderburkjim

**Comment by funderburkjim** [comment]
Greek text installed - See above commit.
Thanks, @jmigliori !
