### ISSUE TITLE
Greek text in GST dictionary

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#38]
gst = Goldstücker Sanskrit-English Dictionary

@jmigliori 

See if you can work with this file:
[gst_greek.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7147050/gst_greek.txt)

* The file gives the entry digitization for each entry that has Greek text.
   * some entries may have more than one line with Greek text, e.g. anurADa
* Each entry provides a pdf link that you can paste into browser url.
* Also, since the headwords in the pdf show as Devanagari,  the file also shows the Devanagari headword
   * this, along with the page column (a or b), may help you get to the right spot in the scan
* The lines with Greek text are preceded and followed by a blank line.
   * The greek text spots are identified by `<lang n="greek"></lang>`
   * Your task is to edit the file, and insert the Greek text :  `<lang n="greek">GREEK TEXT HERE</lang>`

Let me know if this format is useable.  If it is, then I'll make a similar file for VEI.

**Comment by funderburkjim** [comment]
Here is a sample entry from the gst_greek.txt file
```
; ----------------------------------------------------------
; pdf link = https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=gst&page=070-b
; headword = अनफा
; ----------------------------------------------------------
<L>2350<pc>070-b<k1>anaPA<k2>anaPA
{#anaPA#}¦ f. ({#-PA#}) A certain configuration of the planets; a

<div n="lb">transcription of the greek word <lang n="greek"></lang>.

<LEND>
```

**Comment by funderburkjim** [comment]
Note also some lines may have greek text in more than one spot
```
<div n="lb">and the asterism probably comprises <lang n="greek"></lang> and <lang n="greek"></lang> Scorpionis.
```

**Comment by jmigliori** [comment]
This format is very useable!

**Comment by jmigliori** [comment]
all set!

[gst_greek-complete.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7149757/gst_greek-complete.txt)

**Comment by funderburkjim** [comment]
Work looks good. Will install soon.

**Comment by funderburkjim** [comment]
Greek text installed.

@jmigliori gst greek text task finished.
