### ISSUE TITLE
Greek in BUR

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#39]
When we tackle coding of Greek text in Burnouf dictionary ...

Investigate this further:  https://github.com/sanskrit-lexicon/csl-orig/issues/607#issuecomment-914916287 

(Ref: https://github.com/sanskrit-lexicon/GreekInSanskrit/issues/33#issuecomment-917417616)

**Comment by Andhrabharati** [comment]
These are (mostly) within the italic strings {%...%} as I noticed, without Greek tagging.

**Comment by Andhrabharati** [comment]
The greek text has been added into csl text by Jim, and the issue can be closed now.
