### ISSUE TITLE
Greek text in VEI dictionary

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#40]
vei = Vedic Index of Names and Subjects

@jmigliori 

Here is the file for the VEI Greek text input:

[vei_greek.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7150207/vei_greek.txt)

The format is similar to that described for GST dictionary in #38.

Two minor differences:  
* The headword is shown in IAST, a close approximation to that of the scanned image
* on the 'greek' lines,  there appears the internal line number  in the digitization -- this will be used by me to generate 
   change transactions to update the vei.txt digitization. For example the '24000 ' in
   `24000 <div n="lb"/>and the Greek <lang n="greek"></lang>, Lang, {%Homer and%}`

**Comment by jmigliori** [comment]
[vei_greek-corrected.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7164511/vei_greek-corrected.txt)

Lots of star names here; I had to check some astronomical charts to make sure everything was right for the places where the scan was unclear.

There were four instances where lowercase alphas were tagged as lowercase italic “a”s. I retagged them as Greek. They’re in lines 25235, 25339, 25340, and 44180.

There’s a character tagged as Greek in line 62062 that I’m pretty sure isn’t Greek (it’s part of a series of lowercase Roman numerals). I can’t tell exactly what it is though.

**Comment by funderburkjim** [comment]
> the 62062 line.

This occurs as a footnote under headword sUrya, 
https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=vei&page=2-466

![image](https://user-images.githubusercontent.com/6393033/133357833-ee3416f8-f365-4b49-bd38-230a13b40a17.png)

I think the suspect letter (which looks a little like a Greek lambda, but, as Jonathan says, certainly is not)
is most likely a poorly printed semicolon.   `; 138, 4` would refer to verse 4 of hymn 138  in maṇḍala x (10).

And 10,138,4 does refer to sUrya:
https://sanskrit-lexicon.github.io/rvlinks/rvhymns/rv10.138.html 

@Andhrabharati   Agree?

Incidentally, in [10,37,3](https://sanskrit-lexicon.github.io/rvlinks/rvhymns/rv10.037.html) , English translation,
there is a typo : 'cast' should be 'east', I think.

**Comment by funderburkjim** [comment]
Agree with changing of `{%a%}` to `<lang n="greek">α</lang>` in the 4 lines 25235, etc.

**Comment by funderburkjim** [comment]
Corrections now installed.

Another one bites the dust!

Thanks, @jmigliori

**Comment by Andhrabharati** [comment]
Migliori got it right-
![image](https://user-images.githubusercontent.com/75209130/133370894-11a364bc-7d35-46da-8f29-a9fa0a422a55.png)

yes, प्राचीन indicates प्राक् the East here at 10.37.3

**Comment by Andhrabharati** [comment]
> where the scan was unclear.

this speaks for the need to have good scans/books.

**Comment by funderburkjim** [comment]
@Andhrabharati  Your scan much clearer.  Where can we get ?

**Comment by Andhrabharati** [comment]
archive.org has it in two parts, @funderburkjim. (Guess you can find it easily!!)
