### ISSUE TITLE
Greek text in Benfey

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#41]
This issue similar to #33 , but will be restricted to Benfey Greek text.
Current expectation is that when his time permits, @jmigliori will so indicate in a comment in this issue,
and preparation of needed material for his work will proceed then.

**Comment by Andhrabharati** [comment]
I am taking liberties to take-up this job now; hope it doesn't hurt anyone over here!

However, this will be done in the Devanagari file I had posted recently (with a slightly different format), not in the Cologne format.

**Comment by Andhrabharati** [comment]
Hope Jim would be looking into my BEN file, to fill up the greek text strings into csl file soon; hence, closing the issue now.

**Comment by funderburkjim** [comment]
Yes, I should do this to get it out of the way.  Refer https://github.com/sanskrit-lexicon/BEN/issues/6.
