### ISSUE TITLE
Greek text boesp (notes and addenda)

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/GreekInSanskrit#42]
In https://github.com/funderburkjim/boesp-prep/issues/16,  @Andhrabharati has prepared 
pdfs and text files for Greek text from notes and addenda in boesp, for all three volumes.

These are not filled in.

@jmigliori  Take a look and see if you have time to do these.

I see that you've finished the VEI and other two dictionary Greek text,  as well as the boesp verses.
Really appreciate your gracious help.

I think this boesp task is the last 'just one more thing' that we'll confront you with for now!

Links to local copies of relevant files in next comment.

**Comment by funderburkjim** [comment]
[Greek.Notes.and.Addenda.boesp-1.pdf](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7165504/Greek.Notes.and.Addenda.boesp-1.pdf)
[Greek.Notes.and.Addenda.boesp-2.pdf](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7165506/Greek.Notes.and.Addenda.boesp-2.pdf)
[Greek.Notes.and.Addenda.boesp-3.pdf](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7165507/Greek.Notes.and.Addenda.boesp-3.pdf)

[Greek.Notes.and.Addenda.in.boesp-1.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7165508/Greek.Notes.and.Addenda.in.boesp-1.txt)
[Greek.Notes.and.Addenda.in.boesp-2.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7165509/Greek.Notes.and.Addenda.in.boesp-2.txt)
[Greek.Notes.and.Addenda.in.boesp-3.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7165510/Greek.Notes.and.Addenda.in.boesp-3.txt)

In my glance at the first volume,  I think there may be enough context for you to work with,
even though there are occasional 1-letter snips of Greek.  Let us know if any identification problems
arise.

**Comment by jmigliori** [comment]
[Greek.Notes.and.Addenda.in.boesp-1-corrected.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7178926/Greek.Notes.and.Addenda.in.boesp-1-corrected.txt)
[Greek.Notes.and.Addenda.in.boesp-2-corrected.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7178925/Greek.Notes.and.Addenda.in.boesp-2-corrected.txt)
[Greek.Notes.and.Addenda.in.boesp-3-corrected.txt](https://github.com/sanskrit-lexicon/GreekInSanskrit/files/7178927/Greek.Notes.and.Addenda.in.boesp-3-corrected.txt)

All set

**Comment by funderburkjim** [comment]
@jmigliori Thanks again for all the recent help.

Drop me a comment in several months or whenever you have time for tackling the Greek text in remaining dictionaries.

So long til then.

**Comment by jmigliori** [comment]
My pleasure. Will do!
