### ISSUE TITLE
MW questions

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/GreekInSanskrit#43]
While handling file given by @Andhrabharati ,
I came across the following differences. 
The suggestion of digitization by AB seems to be fine to me visually. Presently the text is shown as '*᾿αμιτροχάτης'. Whereas, suggested reading is '᾿Aμιτροχάτης'. 
Somewhat like capitalization of Greek. I am not sure about conventions of Greek.

```
<s>अमि/त्र—घात</s> ¦ <lex>m.</lex> (= <lang n="greek">*᾿αμιτροχάτης</lang>) <ab>N.</ab> of <s1 slp1="bindusAra">Bindusāra</s1> (the son of <s1 slp1="candragupta">Candragupta</s1>). <info lex="m"/>
```

**Comment by Andhrabharati** [comment]
My first suggestion is to go by the book content; and in case of any doubt, to consult the Greek expert @jmigliori, who is always helpful!

**Comment by Andhrabharati** [comment]
Probably, I might've used the English Capital letters, being similar to the Greek capitals; guess it is appropriate to change those to Greek letters.

https://www.rapidtables.com/math/symbols/greek_alphabet.html

**Comment by Andhrabharati** [comment]
The suggested correction (᾿Aμιτροχάτης) is there in mw now; so the issue can be closed now.
